// <auto-generated />
using System;
using ConferenceBooking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConferenceBooking.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ConferenceBookingDbContext))]
    [Migration("20260907101201_SeedConferenceBookingData")]
    partial class SeedConferenceBookingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.BaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ConferenceBooking.Infrastructure.Idempotency.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Location")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ResponseContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Operation", "Key")
                        .IsUnique();

                    b.ToTable("IdempotencyKeys", (string)null);
                });

            modelBuilder.Entity("ConferenceHallAdditionalService", b =>
                {
                    b.Property<Guid>("ConferenceHallId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdditionalServiceId")
                        .HasColumnType("uuid");

                    b.HasKey("ConferenceHallId", "AdditionalServiceId");

                    b.HasIndex("AdditionalServiceId");

                    b.ToTable("ConferenceHallAdditionalServices", (string)null);

                    b.HasData(
                        new
                        {
                            ConferenceHallId = new Guid("b7e4a1c9-5d23-4f86-9a10-2c6e8d3b7f55"),
                            AdditionalServiceId = new Guid("d8b8f4d4-3a6f-4f78-9f5a-7e1c9b2a4d11")
                        },
                        new
                        {
                            ConferenceHallId = new Guid("b7e4a1c9-5d23-4f86-9a10-2c6e8d3b7f55"),
                            AdditionalServiceId = new Guid("a4c2e7b1-6d90-4b35-8f21-3c7a5e9d2b44")
                        },
                        new
                        {
                            ConferenceHallId = new Guid("b7e4a1c9-5d23-4f86-9a10-2c6e8d3b7f55"),
                            AdditionalServiceId = new Guid("f1e3b6c8-2a54-4d97-8b30-6e9c5a7d1f22")
                        },
                        new
                        {
                            ConferenceHallId = new Guid("c9f2d6a8-1b47-4e03-8c65-5a7d9f2b6e88"),
                            AdditionalServiceId = new Guid("d8b8f4d4-3a6f-4f78-9f5a-7e1c9b2a4d11")
                        },
                        new
                        {
                            ConferenceHallId = new Guid("c9f2d6a8-1b47-4e03-8c65-5a7d9f2b6e88"),
                            AdditionalServiceId = new Guid("a4c2e7b1-6d90-4b35-8f21-3c7a5e9d2b44")
                        },
                        new
                        {
                            ConferenceHallId = new Guid("c9f2d6a8-1b47-4e03-8c65-5a7d9f2b6e88"),
                            AdditionalServiceId = new Guid("f1e3b6c8-2a54-4d97-8b30-6e9c5a7d1f22")
                        },
                        new
                        {
                            ConferenceHallId = new Guid("e3a5c7f9-8d12-4b64-9e30-1a6c5d7b2f99"),
                            AdditionalServiceId = new Guid("d8b8f4d4-3a6f-4f78-9f5a-7e1c9b2a4d11")
                        },
                        new
                        {
                            ConferenceHallId = new Guid("e3a5c7f9-8d12-4b64-9e30-1a6c5d7b2f99"),
                            AdditionalServiceId = new Guid("a4c2e7b1-6d90-4b35-8f21-3c7a5e9d2b44")
                        },
                        new
                        {
                            ConferenceHallId = new Guid("e3a5c7f9-8d12-4b64-9e30-1a6c5d7b2f99"),
                            AdditionalServiceId = new Guid("f1e3b6c8-2a54-4d97-8b30-6e9c5a7d1f22")
                        });
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.AdditionalService", b =>
                {
                    b.HasBaseType("ConferenceBooking.Domain.Entities.BaseEntity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.ToTable("AdditionalServices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8b8f4d4-3a6f-4f78-9f5a-7e1c9b2a4d11"),
                            IsDeleted = false,
                            Name = "Projector",
                            Price = 500m
                        },
                        new
                        {
                            Id = new Guid("a4c2e7b1-6d90-4b35-8f21-3c7a5e9d2b44"),
                            IsDeleted = false,
                            Name = "Wi-Fi",
                            Price = 300m
                        },
                        new
                        {
                            Id = new Guid("f1e3b6c8-2a54-4d97-8b30-6e9c5a7d1f22"),
                            IsDeleted = false,
                            Name = "Sound",
                            Price = 700m
                        });
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.Booking", b =>
                {
                    b.HasBaseType("ConferenceBooking.Domain.Entities.BaseEntity");

                    b.Property<Guid>("ConferenceHallId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HallCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("HallHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("HallName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalServicesCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasIndex("ConferenceHallId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.BookingService", b =>
                {
                    b.HasBaseType("ConferenceBooking.Domain.Entities.BaseEntity");

                    b.Property<Guid>("AdditionalServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasIndex("AdditionalServiceId");

                    b.HasIndex("BookingId", "AdditionalServiceId")
                        .IsUnique();

                    b.ToTable("BookingServices", (string)null);
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.ConferenceHall", b =>
                {
                    b.HasBaseType("ConferenceBooking.Domain.Entities.BaseEntity");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("RentRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.ToTable("ConferenceHalls", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7e4a1c9-5d23-4f86-9a10-2c6e8d3b7f55"),
                            IsDeleted = false,
                            Capacity = 50,
                            Name = "Hall A",
                            RentRate = 2000m
                        },
                        new
                        {
                            Id = new Guid("c9f2d6a8-1b47-4e03-8c65-5a7d9f2b6e88"),
                            IsDeleted = false,
                            Capacity = 100,
                            Name = "Hall B",
                            RentRate = 3500m
                        },
                        new
                        {
                            Id = new Guid("e3a5c7f9-8d12-4b64-9e30-1a6c5d7b2f99"),
                            IsDeleted = false,
                            Capacity = 30,
                            Name = "Hall C",
                            RentRate = 1500m
                        });
                });

            modelBuilder.Entity("ConferenceHallAdditionalService", b =>
                {
                    b.HasOne("ConferenceBooking.Domain.Entities.AdditionalService", null)
                        .WithMany()
                        .HasForeignKey("AdditionalServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConferenceBooking.Domain.Entities.ConferenceHall", null)
                        .WithMany()
                        .HasForeignKey("ConferenceHallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.Booking", b =>
                {
                    b.HasOne("ConferenceBooking.Domain.Entities.ConferenceHall", "ConferenceHall")
                        .WithMany("Bookings")
                        .HasForeignKey("ConferenceHallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConferenceHall");
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.BookingService", b =>
                {
                    b.HasOne("ConferenceBooking.Domain.Entities.AdditionalService", "AdditionalService")
                        .WithMany()
                        .HasForeignKey("AdditionalServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConferenceBooking.Domain.Entities.Booking", "Booking")
                        .WithMany("AdditionalServices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdditionalService");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.Booking", b =>
                {
                    b.Navigation("AdditionalServices");
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.ConferenceHall", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
